const mongoose=require("mongoose")

const resumeSchema = new mongoose.Schema(
    {
        userId:{
            type:mongoose.Schema.Types.ObjectId,
            required:true,
            ref:"user"
        },
        name:{
            type:String,
            required:true
        },
        email:{
            type:String,
            required:true
        },
        phone:{
            type:String,
            required:true
        },
        housename:{
            type:String,
            required:true
        },
        place:{
            type:String,
            required:true
        },
        pincode:{
            type:String,
            required:true
        },
        district:{
            type:String,
            required:true
        },
        gender:{
            type:String,
            required:true
        },
        age:{
            type:String,
            required:true
        },
        qualification:{
            type:String,
            required:true
        },
        skills:{
            type:String,
            required:true
        },
        achievements:{
            type:String,
            required:true
        },
        certifications:{
            type:String,
            required:true
        },
        hobbies:{
            type:String,
            required:true
        },
        referencename:{
            type:String,
            required:true
        },
        referencequal:{
            type:String,
            required:true
        },
        referencenum:{
            type:String,
            required:true
        }
    }
)

module.exports=mongoose.model("resume",resumeSchema)